import {
  siAdobe,
  siAlgolia,
  siAmazon,
  siAmazonaws,
  siApachemaven,
  siAppstore,
  siAtlassian,
  siBlogger,
  siCloudflare,
  siCnn,
  siCodesandbox,
  siDeezer,
  siDigitalocean,
  siDiscord,
  siDuckduckgo,
  siFacebook,
  siFandom,
  siFastly,
  siFigma,
  siFirebase,
  siGithub,
  siGitlab,
  siGmail,
  siGoogle,
  siGoogleclassroom,
  siGooglecloud,
  siGoogledrive,
  siImdb,
  siImgur,
  siInstagram,
  siJenkins,
  siJsdelivr,
  siLine,
  siLinear,
  siLinkedin,
  siLinode,
  siMailchimp,
  siMediafire,
  siMessenger,
  siMicrosoft,
  siMicrosoftazure,
  siMicrosoftoffice,
  siMicrosoftsharepoint,
  siNetflix,
  siNetlify,
  siNewyorktimes,
  siNotion,
  siNpm,
  siOvh,
  siPatreon,
  siPaypal,
  siPinterest,
  siPolywork,
  siPypi,
  siQuora,
  siReddit,
  siRoblox,
  siSlack,
  siSoundcloud,
  siSpotify,
  siStackoverflow,
  siStatuspage,
  siSteam,
  siSurveymonkey,
  siTelegram,
  siTiktok,
  siTokopedia,
  siTrello,
  siTumblr,
  siTwilio,
  siTwitch,
  siTwitter,
  siVercel,
  siVultr,
  siWaze,
  siWhatsapp,
  siWikipedia,
  siWordpress,
  siYahoo,
  siYoutube,
  siZoho,
  siZoom,
  siBitbucket
} from 'simple-icons/icons'

import {
  alodokterIcon,
  bcaIcon,
  brainlyIcon,
  danaIcon,
  gojekIcon,
  halodocIcon,
  hotstarIcon,
  jeniusIcon,
  lazadaIcon,
  mangakuIcon,
  mobileLegendsIcon,
  ovoIcon,
  shopeeIcon,
  telkomselIcon,
  tokopediaIcon,
  travelokaIcon,
  vidioComIcon,
  zeniusIcon
} from './_icons'

export const devStarterPack = [
  // Code storage
  { website: 'github.com', icon: siGithub },
  { website: 'gitlab.com', icon: siGitlab },
  { website: 'bitbucket.org', icon: siBitbucket },
  // Libs
  { website: 'pypi.org', icon: siPypi },
  { website: 'npmjs.com', icon: siNpm },
  { website: 'maven.apache.org', icon: siApachemaven },
  // Services
  { website: 'firebase.google.com', icon: siFirebase },
  { website: 'cloudflare.com', icon: siCloudflare },
  { website: 'google.com', icon: siGooglecloud },
  { website: 'https://aws.amazon.com', icon: siAmazonaws },
  { website: 'azure.com', icon: siMicrosoftazure },
  { website: 'vercel.com', icon: siVercel },
  { website: 'netlify.com', icon: siNetlify },
  { website: 'digitalocean.com', icon: siDigitalocean },
  { website: 'vultr.com', icon: siVultr },
  { website: 'linode.com', icon: siLinode },
  { website: 'ovh.com', icon: siOvh },
  { website: 'cdn.jsdelivr.net', icon: siJsdelivr },
  { website: 'fastly.com', icon: siFastly },
  { website: 'algolia.com', icon: siAlgolia },
  // SocMed
  { website: 'slack.com', icon: siSlack },
  { website: 'linkedin.com', icon: siLinkedin },
  { website: 'polywork.com', icon: siPolywork },
  { website: 'stackoverflow.com', icon: siStackoverflow },
  { website: 'statuspage.io', icon: siStatuspage },
  // Design
  { website: 'figma.com', icon: siFigma },
  { website: 'adobe.com', icon: siAdobe },
  { website: 'codesandbox.io', icon: siCodesandbox },
  // Docs
  { website: 'notion.com', icon: siNotion },
  { website: 'trello.com', icon: siTrello },
  { website: 'atlassian.com', icon: siAtlassian },
  { website: 'linear.org', icon: siLinear },
  // Email
  { website: 'gmail.com', icon: siGmail },
  { website: 'zoho.com', icon: siZoho },
  { website: 'mailchimp.com', icon: siMailchimp },
  { website: 'twilio.com', icon: siTwilio }
]

// export const game = [
//   { website: 'pubg.com', icon: siPubg },
//   { website: 'pubg.com', icon: siCrossfire },
//   { website: 'roblox.com', icon: siRoblox }
// ]

export const idnStarterPack = [
  { website: 'line.me', icon: siLine },
  { website: 'web.whatsapp.com', icon: siWhatsapp },
  { website: 'https://www.ovo.id/', icon: ovoIcon },
  { website: 'tiktok.com', icon: siTiktok },
  { website: 'google.com', icon: siGoogle },
  { website: 'facebook.com', icon: siFacebook },
  { website: 'twitter.com', icon: siTwitter },
  { website: 'instagram.com', icon: siInstagram },
  { website: 'messenger.com', icon: siMessenger },
  { website: 'wikipedia.org', icon: siWikipedia },
  { website: 'gojek.com', icon: gojekIcon },
  { website: 'dana.id', icon: danaIcon },
  { website: 'web.telegram.org', icon: siTelegram },
  { website: 'spotify.com', icon: siSpotify },
  { website: 'deezer.com', icon: siDeezer },
  { website: 'https://www.telkomsel.com/', icon: telkomselIcon },
  { website: 'waze.com', icon: siWaze },
  { website: 'tokopedia.com', icon: tokopediaIcon },
  { website: 'shopee.co.id', icon: shopeeIcon },
  { website: 'www.lazada.co.id', icon: lazadaIcon },
  { website: 'traveloka.co.id', icon: travelokaIcon },
  { website: 'bca.co.id', icon: bcaIcon },
  { website: 'classroom.google.com', icon: siGoogleclassroom },
  { website: 'drive.google.com', icon: siGoogledrive },
  { website: 'brainly.co.id', icon: brainlyIcon },
  { website: 'gmail.com', icon: siGmail },
  { website: 'netflix.com', icon: siNetflix },
  { website: 'hotstar.com', icon: hotstarIcon },
  { website: 'notion.com', icon: siNotion },
  { website: 'pinterest.com', icon: siPinterest },
  { website: 'soundcloud.com', icon: siSoundcloud },
  { website: 'www.zenius.net', icon: zeniusIcon },
  { website: 'paypal.com', icon: siPaypal },
  { website: '2secure.jenius.co.id', icon: jeniusIcon },
  { website: 'steampowered.com', icon: siSteam },
  { website: 'play.google.com/store/apps/details?id=com.mobile.legends', icon: mobileLegendsIcon },
  { website: 'linkedin.com', icon: siLinkedin },
  { website: 'www.alodokter.com', icon: alodokterIcon },
  { website: 'mangaku.com', icon: mangakuIcon },
  { website: 'roblox.com', icon: siRoblox },
  { website: 'www.halodoc.com', icon: halodocIcon },
  { website: 'mediafire.com', icon: siMediafire },
  { website: 'www.vidio.com', icon: vidioComIcon },
  { website: 'www.tokopedia.com', icon: siTokopedia}.
  // { website: 'kemdikbud.go.id', icon: kemdikbudIcon },
  // { website: 'kominfo.go.id', icon: kominfoIcon },
  // { website: 'kemkes.go.id', icon: pedulilindungiIcon }
]

export const websiteListUSA = [
  { website: 'google.com', icon: siGoogle },
  { website: 'youtube.com', icon: siYoutube },
  { website: 'facebook.com', icon: siFacebook },
  { website: 'amazon.com', icon: siAmazon },
  { website: 'apps.apple.com', icon: siAppstore },
  { website: 'reddit.com', icon: siReddit },
  { website: 'wikipedia.org', icon: siWikipedia },
  { website: 'yahoo.com', icon: siYahoo },
  { website: 'twitter.com', icon: siTwitter },
  { website: 'instagram.com', icon: siInstagram },
  { website: 'web.whatsapp.com', icon: siWhatsapp },
  { website: 'discord.com', icon: siDiscord },
  { website: 'twitch.tv', icon: siTwitch },
  { website: 'zoom.us', icon: siZoom },
  { website: 'roblox.com', icon: siRoblox },
  { website: 'duckduckgo.com', icon: siDuckduckgo },
  { website: 'paypal.com', icon: siPaypal },
  { website: 'fandom.com', icon: siFandom },
  { website: 'linkedin.com', icon: siLinkedin },
  { website: 'quora.com', icon: siQuora },
  { website: 'imdb.com', icon: siImdb },
  { website: 'cnnindonesia.com', icon: siCnn },
  { website: 'tiktok.com', icon: siTiktok },
  { website: 'office.com', icon: siMicrosoftoffice },
  { website: 'microsoft.com', icon: siMicrosoft },
  { website: 'netflix.com', icon: siNetflix },
  { website: 'pinterest.com', icon: siPinterest },
  { website: 'imgur.com', icon: siImgur },
  { website: 'tumblr.com', icon: siTumblr },
  { website: 'github.com', icon: siGithub },
  { website: 'stackoverflow.com', icon: siStackoverflow },
  { website: 'wordpress.com', icon: siWordpress },
  { website: 'blogspot.com', icon: siBlogger },
  { website: 'adobe.com', icon: siAdobe },
  { website: 'nypost.com', icon: siNewyorktimes },
  { website: 'sharepoint.com', icon: siMicrosoftsharepoint },
  { website: 'patreon.com', icon: siPatreon },
  { website: 'surveymonkey.com', icon: siSurveymonkey }
]
