import type { SimpleIcon } from 'simple-icons'
import {
  siAdafruit,
  siAdobe,
  siAlgolia,
  siAmazon,
  siAmazonaws,
  siApachemaven,
  siAppstore,
  siArchlinux,
  siArduino,
  siAtlassian,
  siAutodesk,
  siBitbucket,
  siBlender,
  siBlogger,
  siChocolatey,
  siCloudflare,
  siCnn,
  siCodecademy,
  siCodesandbox,
  siCodingame,
  siDebian,
  siDeezer,
  siDigitalocean,
  siDiscord,
  siDuckduckgo,
  siEa,
  siEpicgames,
  siFacebook,
  siFandom,
  siFastly,
  siFigma,
  siFirebase,
  siFreecodecamp,
  siGithub,
  siGitlab,
  siGmail,
  siGodotengine,
  siGoogle,
  siGoogleclassroom,
  siGooglecloud,
  siGoogledrive,
  siGooglemaps,
  siHackerrank,
  siImdb,
  siImgur,
  siInstagram,
  siJenkins,
  siJsdelivr,
  siKalilinux,
  siLeetcode,
  siLine,
  siLinear,
  siLinkedin,
  siLinktree,
  siLinode,
  siLinux,
  siMailchimp,
  siMediafire,
  siMessenger,
  siMicrosoft,
  siMicrosoftazure,
  siMicrosoftoffice,
  siMicrosoftsharepoint,
  siNetflix,
  siNetlify,
  siNewyorktimes,
  siNintendo,
  siNotion,
  siNpm,
  siOvh,
  siPatreon,
  siPaypal,
  siPinterest,
  siPolywork,
  siPypi,
  siQuora,
  siReadthedocs,
  siReddit,
  siRoblox,
  siScratch,
  siSlack,
  siSololearn,
  siSoundcloud,
  siSpotify,
  siStackexchange,
  siStackoverflow,
  siStatuspage,
  siSteam,
  siStmicroelectronics,
  siSurveymonkey,
  siTelegram,
  siTiktok,
  siTrello,
  siTumblr,
  siTwilio,
  siTwitch,
  siTwitter,
  siUbisoft,
  siUbuntu,
  siUnity,
  siUnrealengine,
  siVercel,
  siVultr,
  siWaze,
  siWhatsapp,
  siWikipedia,
  siWordpress,
  siYahoo,
  siYoutube,
  siZoho,
  siZoom
} from 'simple-icons/icons'

import {
  alodokterIcon,
  bcaIcon,
  brainlyIcon,
  components101Icon,
  danaIcon,
  devDocsIcon,
  gojekIcon,
  halodocIcon,
  hotstarIcon,
  jeniusIcon,
  lazadaIcon,
  mangakuIcon,
  mobileLegendsIcon,
  nodeMCUIcon,
  ovoIcon,
  shopeeIcon,
  telkomselIcon,
  tokopediaIcon,
  travelokaIcon,
  ubuntuArchivesIcon,
  vidioComIcon,
  w3SchoolsIcon,
  zeniusIcon
} from './_icons'

export interface WebsiteData {
  website: string
  icon: SimpleIcon
}

export const devStarterPack = [
  // Code storage
  { website: 'github.com', icon: siGithub },
  { website: 'gitlab.com', icon: siGitlab },
  { website: 'bitbucket.org', icon: siBitbucket },
  // Libs
  { website: 'pypi.org', icon: siPypi },
  { website: 'npmjs.com', icon: siNpm },
  { website: 'maven.apache.org', icon: siApachemaven },
  // Services
  { website: 'google.com', icon: siFirebase },
  { website: 'cloudflare.com', icon: siCloudflare },
  { website: 'google.com', icon: siGooglecloud },
  { website: 'aws.amazon.com', icon: siAmazonaws },
  { website: 'azure.com', icon: siMicrosoftazure },
  { website: 'vercel.com', icon: siVercel },
  { website: 'netlify.com', icon: siNetlify },
  { website: 'digitalocean.com', icon: siDigitalocean },
  { website: 'vultr.com', icon: siVultr },
  { website: 'linode.com', icon: siLinode },
  { website: 'ovh.com', icon: siOvh },
  { website: 'cdn.jsdelivr.net', icon: siJsdelivr },
  { website: 'fastly.com', icon: siFastly },
  { website: 'algolia.com', icon: siAlgolia },
  // Game Engines
  { website: 'unity.com', icon: siUnity },
  { website: 'unrealengine.com', icon: siUnrealengine },
  { website: 'godotengine.org', icon: siGodotengine },
  // 3D Modelling | Animation
  { website: 'autodesk.com', icon: siAutodesk },
  { website: 'blender.org', icon: siBlender },
  // Microcontroller
  { website: 'arduino.cc', icon: siArduino },
  { website: 'adafruit.com', icon: siAdafruit },
  { website: 'www.nodemcu.com', icon: nodeMCUIcon },
  { website: 'st.com', icon: siStmicroelectronics },
  // SocMed
  { website: 'slack.com', icon: siSlack },
  { website: 'linkedin.com', icon: siLinkedin },
  { website: 'polywork.com', icon: siPolywork },
  { website: 'stackexchange.com', icon: siStackexchange },
  { website: 'stackoverflow.com', icon: siStackoverflow },
  { website: 'statuspage.io', icon: siStatuspage },
  // Coding Tutorials
  { website: 'codecademy.com', icon: siCodecademy },
  { website: 'freecodecamp.org', icon: siFreecodecamp },
  { website: 'sololearn.com', icon: siSololearn },
  { website: 'scratch.mit.edu', icon: siScratch },
  { website: 'w3schools.com', icon: w3SchoolsIcon },
  // Competitive Programming/Training
  { website: 'codingame.com', icon: siCodingame },
  { website: 'hackerrank.com', icon: siHackerrank },
  { website: 'leetcode.com', icon: siLeetcode },
  // Design
  { website: 'figma.com', icon: siFigma },
  { website: 'adobe.com', icon: siAdobe },
  { website: 'codesandbox.io', icon: siCodesandbox },
  // Docs
  { website: 'notion.com', icon: siNotion },
  { website: 'trello.com', icon: siTrello },
  { website: 'atlassian.com', icon: siAtlassian },
  { website: 'linear.org', icon: siLinear },
  { website: 'devdocs.io', icon: devDocsIcon },
  { website: 'readthedocs.org', icon: siReadthedocs },
  // Electronic Component Docs
  { website: 'components101.com', icon: components101Icon },
  // Email
  { website: 'google.com', icon: siGmail },
  { website: 'zoho.com', icon: siZoho },
  { website: 'mailchimp.com', icon: siMailchimp },
  { website: 'twilio.com', icon: siTwilio },
  // Package Manager
  { website: 'community.chocolatey.org', icon: siChocolatey },
  { website: 'us.archive.ubuntu.com', icon: ubuntuArchivesIcon }
]

// export const game = [
//   { website: 'pubg.com', icon: siPubg },
//   { website: 'pubg.com', icon: siCrossfire },
//   { website: 'roblox.com', icon: siRoblox },
//   { website: 'ea.com', icon: siEa},
//   { website: 'epicgames.com', icon: siEpicgames},
//   { website: 'nintendo.com', icon: siNintendo},
//   { website: 'ubisoft.com', icon: siUbisoft}
//   { website: 'steampowered.com', icon: siSteam },
// ]

export const idnStarterPack = [
  { website: 'line.me', icon: siLine },
  { website: 'web.whatsapp.com', icon: siWhatsapp },
  { website: 'www.ovo.id', icon: ovoIcon },
  { website: 'tiktok.com', icon: siTiktok },
  { website: 'google.com', icon: siGoogle },
  { website: 'facebook.com', icon: siFacebook },
  { website: 'twitter.com', icon: siTwitter },
  { website: 'instagram.com', icon: siInstagram },
  { website: 'messenger.com', icon: siMessenger },
  { website: 'wikipedia.org', icon: siWikipedia },
  { website: 'gojek.com', icon: gojekIcon },
  { website: 'dana.id', icon: danaIcon },
  { website: 'web.telegram.org', icon: siTelegram },
  { website: 'spotify.com', icon: siSpotify },
  { website: 'deezer.com', icon: siDeezer },
  { website: 'www.telkomsel.com', icon: telkomselIcon },
  { website: 'google.com', icon: siGooglemaps },
  { website: 'waze.com', icon: siWaze },
  { website: 'tokopedia.com', icon: tokopediaIcon },
  { website: 'shopee.co.id', icon: shopeeIcon },
  { website: 'www.lazada.co.id', icon: lazadaIcon },
  { website: 'traveloka.co.id', icon: travelokaIcon },
  { website: 'bca.co.id', icon: bcaIcon },
  { website: 'google.com', icon: siGoogleclassroom },
  { website: 'google.com', icon: siGoogledrive },
  { website: 'brainly.co.id', icon: brainlyIcon },
  { website: 'google.com', icon: siGmail },
  { website: 'netflix.com', icon: siNetflix },
  { website: 'hotstar.com', icon: hotstarIcon },
  { website: 'notion.com', icon: siNotion },
  { website: 'pinterest.com', icon: siPinterest },
  { website: 'soundcloud.com', icon: siSoundcloud },
  { website: 'www.zenius.net', icon: zeniusIcon },
  { website: 'paypal.com', icon: siPaypal },
  { website: '2secure.jenius.co.id', icon: jeniusIcon },
  { website: 'ea.com', icon: siEa },
  { website: 'epicgames.com', icon: siEpicgames },
  { website: 'nintendo.com', icon: siNintendo },
  { website: 'steampowered.com', icon: siSteam },
  { website: 'ubisoft.com', icon: siUbisoft },
  { website: 'play.google.com/store/apps/details?id=com.mobile.legends', icon: mobileLegendsIcon },
  { website: 'linkedin.com', icon: siLinkedin },
  { website: 'www.alodokter.com', icon: alodokterIcon },
  { website: 'mangaku.com', icon: mangakuIcon },
  { website: 'roblox.com', icon: siRoblox },
  { website: 'www.halodoc.com', icon: halodocIcon },
  { website: 'mediafire.com', icon: siMediafire },
  { website: 'www.vidio.com', icon: vidioComIcon },
  { website: 'linktr.ee', icon: siLinktree }
  // { website: 'kemdikbud.go.id', icon: kemdikbudIcon },
  // { website: 'kominfo.go.id', icon: kominfoIcon },
  // { website: 'kemkes.go.id', icon: pedulilindungiIcon }
]

export const websiteListUSA = [
  { website: 'google.com', icon: siGoogle },
  { website: 'google.com', icon: siYoutube },
  { website: 'facebook.com', icon: siFacebook },
  { website: 'amazon.com', icon: siAmazon },
  { website: 'apps.apple.com', icon: siAppstore },
  { website: 'reddit.com', icon: siReddit },
  { website: 'wikipedia.org', icon: siWikipedia },
  { website: 'yahoo.com', icon: siYahoo },
  { website: 'twitter.com', icon: siTwitter },
  { website: 'instagram.com', icon: siInstagram },
  { website: 'web.whatsapp.com', icon: siWhatsapp },
  { website: 'discord.com', icon: siDiscord },
  { website: 'twitch.tv', icon: siTwitch },
  { website: 'zoom.us', icon: siZoom },
  { website: 'roblox.com', icon: siRoblox },
  { website: 'duckduckgo.com', icon: siDuckduckgo },
  { website: 'paypal.com', icon: siPaypal },
  { website: 'fandom.com', icon: siFandom },
  { website: 'linkedin.com', icon: siLinkedin },
  { website: 'quora.com', icon: siQuora },
  { website: 'imdb.com', icon: siImdb },
  { website: 'cnnindonesia.com', icon: siCnn },
  { website: 'tiktok.com', icon: siTiktok },
  { website: 'office.com', icon: siMicrosoftoffice },
  { website: 'microsoft.com', icon: siMicrosoft },
  { website: 'netflix.com', icon: siNetflix },
  { website: 'pinterest.com', icon: siPinterest },
  { website: 'imgur.com', icon: siImgur },
  { website: 'tumblr.com', icon: siTumblr },
  { website: 'github.com', icon: siGithub },
  { website: 'stackoverflow.com', icon: siStackoverflow },
  { website: 'wordpress.com', icon: siWordpress },
  { website: 'blogspot.com', icon: siBlogger },
  { website: 'adobe.com', icon: siAdobe },
  { website: 'nypost.com', icon: siNewyorktimes },
  { website: 'sharepoint.com', icon: siMicrosoftsharepoint },
  { website: 'patreon.com', icon: siPatreon },
  { website: 'surveymonkey.com', icon: siSurveymonkey }
]

export const linuxStarterPack = [
  { website: 'archlinux.org', icon: siArchlinux },
  { website: 'debian.org', icon: siDebian },
  { website: 'kali.org', icon: siKalilinux },
  { website: 'linux.org', icon: siLinux },
  { website: 'ubuntu.com', icon: siUbuntu },
  { website: 'us.archive.ubuntu.com', icon: ubuntuArchivesIcon }
]
