import {
  siAccusoft,
  siAdobe,
  siAmazon,
  siApple,
  siBlogger,
  siCnn,
  siDiscord,
  siDotnet,
  siDuckduckgo,
  siFacebook,
  siFandom,
  siGithub,
  siGoogle,
  siGriddotai,
  siImdb,
  siImgur,
  siInstagram,
  siLinkedin,
  siMediafire,
  siMicrosoft,
  siMicrosoftoffice,
  siMicrosoftsharepoint,
  siNetflix,
  siNewyorktimes,
  siPatreon,
  siPaypal,
  siPinterest,
  siQuora,
  siReddit,
  siRoblox,
  siStackoverflow,
  siSurveymonkey,
  siTiktok,
  siTumblr,
  siTwitch,
  siTwitter,
  siWhatsapp,
  siWikipedia,
  siWordpress,
  siYahoo,
  siYoutube,
  siZoom
} from 'simple-icons/icons'

export const websiteListUSA = [
  { website: 'google.com', icon: siGoogle },
  { website: 'youtube.com', icon: siYoutube },
  { website: 'facebook.com', icon: siFacebook },
  { website: 'amazon.com', icon: siAmazon },
  { website: 'apple.com', icon: siApple },
  { website: 'reddit.com', icon: siReddit },
  { website: 'wikipedia.com', icon: siWikipedia },
  { website: 'yahoo.com', icon: siYahoo },
  { website: 'twitter.com', icon: siTwitter },
  { website: 'instagram.com', icon: siInstagram },
  { website: 'web.whatsapp.com', icon: siWhatsapp },
  { website: 'discord.com', icon: siDiscord },
  { website: 'twitch.tv', icon: siTwitch },
  { website: 'zoom.us', icon: siZoom },
  { website: 'roblox.com', icon: siRoblox },
  { website: 'duckduckgo.com', icon: siDuckduckgo },
  { website: 'paypal.com', icon: siPaypal },
  { website: 'fandom.com', icon: siFandom },
  { website: 'linkedin.com', icon: siLinkedin },
  { website: 'quora.com', icon: siQuora },
  { website: 'imdb.com', icon: siImdb },
  { website: 'cnnindonesia.com', icon: siCnn },
  { website: 'tiktok.com', icon: siTiktok },
  { website: 'office.com', icon: siMicrosoftoffice },
  { website: 'microsoft.com', icon: siMicrosoft },
  { website: 'netflix.com', icon: siNetflix },
  { website: 'pinterest.com', icon: siPinterest },
  { website: 'imgur.com', icon: siImgur },
  { website: 'tumblr.com', icon: siTumblr },
  { website: 'github.com', icon: siGithub },
  { website: 'stackoverflow.com', icon: siStackoverflow },
  { website: 'wordpress.com', icon: siWordpress },
  { website: 'blogspot.com', icon: siBlogger },
  { website: 'adobe.com', icon: siAdobe },
  { website: 'nypost.com', icon: siNewyorktimes },
  { website: 'sharepoint.com', icon: siMicrosoftsharepoint },
  { website: 'patreon.com', icon: siPatreon },
  { website: 'surveymonkey.com', icon: siSurveymonkey }
]

export const websiteListIDN = [
  { website: 'google.com', icon: siGoogle },
  { website: 'youtube.com', icon: siYoutube },
  { website: 'facebook.com', icon: siFacebook },
  { website: 'instagram.com', icon: siInstagram },
  { website: 'web.whatsapp.com', icon: siWhatsapp },
  { website: 'twitter.com', icon: siTwitter },
  { website: 'hotstar.com', icon: siDotnet },
  { website: 'tokopedia.com', icon: siDotnet },
  { website: 'shopee.com', icon: siDotnet },
  { website: 'ppgames.net', icon: siDotnet },
  { website: 'grid.id', icon: siGriddotai },
  { website: 'wikipedia.com', icon: siWikipedia },
  { website: 'brainly.co.id', icon: siDotnet },
  { website: 'tiktok.com', icon: siTiktok },
  { website: 'zoom.us', icon: siZoom },
  { website: 'pinterest.com', icon: siPinterest },
  { website: 'alodokter.com', icon: siDotnet },
  { website: 'mangaku.com', icon: siDotnet },
  { website: 'roblox.com', icon: siRoblox },
  { website: 'kemdikbud.go.id', icon: siDotnet },
  { website: 'halodoc.com', icon: siDotnet },
  { website: 'mediafire.com', icon: siMediafire },
  { website: 'lazada.co.id', icon: siDotnet },
  { website: 'vidio.com', icon: siDotnet }
]
